os: Visual Studio 2015 CTP 6

version: 0.2.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# Before build
install:
- ps: >-
    ./scripts/paket.exe restore
- ps: >-
    ./scripts/SetReleaseVersion.ps1

# Do the build
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- ps: >-
    ./scripts/SetPackageVersions.ps1
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

#---------------------------------#
#      general configuration      #
#---------------------------------#
branches:
  only:
    - master
    - develop

configuration: Release

#---------------------------------#
#        test configuration       #
#---------------------------------#

test:
  assemblies:
    - **\*.Tests.dll

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: NuGet
    artifact: /.*\.nupkg/
    api_key:
      secure: ELbN5jzU0YJ7y3qZsMv6OTGmVVkVgBIaUVkWu2GhamhjCTnYQzNs+VSoXdZWs7Jw
    on:
      branch: master
      appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Slack
    auth_token:
      secure: Q/+09OarQaHIunGaEVxZgMvuge+VbsLEkgwpsPDBLeI4tLT6/JgnAMcAB/Dnay+D
    channel: ci
