os: Visual Studio 2015 CTP 6

version: 0.2.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- nuget restore
- ps: >-
    ./scripts/SetReleaseVersion.ps1
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  verbosity: minimal
after_test:
- ps: >-
    ./scripts/BuildPackages.ps1

#---------------------------------#
#      general configuration      #
#---------------------------------#
branches:
  only:
    - master
    - develop

configuration: Release

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: Nap.nupkg
  - path: Nap.Configuration.nupkg
  - path: Nap.Html.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  provider: NuGet
  api_key: 
    secure: ELbN5jzU0YJ7y3qZsMv6OTGmVVkVgBIaUVkWu2GhamhjCTnYQzNs+VSoXdZWs7Jw
  on:
    branch: master
    appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#

# notifications:
#   - provider: Webhook
#     url:
#       secure: QX1SSnqVH3r4dS+TOE4qU5gwneCjhEfTELkmM+NxetZfYGy2FTyrHdqQk4yXVlIgYndlZLDQ/Dd7TS/3WDTyQT+G7tGqm/e5FsAvcq3SKO06xAIkOhFDu6uZuCxuOSYkUbjc3kUEm1tdXRtTfmMNh64VsSK6ZRq8IXmcoppt6BgucbqSeAyPEob1W8X2Gtnz6QvABnV9p+f7cE9silsXwuRX3pkbZoKF3RkCIMLkiqPl/sPx0S2EjItzV7nz6jgB
#     on_build_failure: true
#     on_build_success: false
#     on_build_status_changed: false
