os: Visual Studio 2015 CTP 6

version: 0.2.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- nuget restore
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  verbosity: minimal
after_test:
- ps: >-
    ./scripts/SetVersion.ps1

# Master branch deployments
branches:
  only:
    - master
  configuration: Release
  deploy:
    provider: Nuget
    api_key: 
      secure: ELbN5jzU0YJ7y3qZsMv6OTGmVVkVgBIaUVkWu2GhamhjCTnYQzNs+VSoXdZWs7Jw
    artifact: /.*\.nupkg/

branches:
  only:
    - develop
  configuration: Debug