os: Visual Studio 2015 CTP 6

version: 0.2.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
init:
- ps: >-
    ./scripts/SetReleaseVersion.ps1
install:
- nuget restore
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  verbosity: minimal
after_test:
- ps: >-
    ./scripts/BuildPackages.ps1

#---------------------------------#
#      general configuration      #
#---------------------------------#
branches:
  only:
    - master
    - develop

configuration: Release

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: /.*\.nupkg/

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  provider: NuGet
  api_key: 
    secure: ELbN5jzU0YJ7y3qZsMv6OTGmVVkVgBIaUVkWu2GhamhjCTnYQzNs+VSoXdZWs7Jw
  artifact: /.*\/.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true